name: CountdownSigns
version: '${version}'
main: cymru.asheiou.countdownsigns.CountdownSigns
api-version: '1.21'
depend:
  - KotKit
commands:
  signadd:
    usage: /<command> <expiry UNIX timestamp>
    permission: countdownsigns.add
    description: Add a sign.
  signremove:
    usage: /<command>
    permission: countdownsigns.remove
    description: Remove a sign.
  signreload:
    usage: /<command>
    permission: countdownsigns.reload
    description: Reload the plugin.
permissions:
  countdownsigns.add:
    default: op
  countdownsigns.remove:
    default: op
  countdownsigns.reload:
    default: op
